# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rswag-specs: .rubocop_rspec_alias_config.yml

plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
FactoryBot/ExcessiveCreateList:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/VariableName:
  AllowedPatterns:
    - ^Authorization$
RSpecRails/InferredSpecType:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: always
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets
Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
