# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpecRails/InferredSpecType:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: always
Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
