require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reviews", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Review. As you add validations to Review, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      content: "hello"
    }
  end

  let(:invalid_attributes) do
    {
      content: nil
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ReviewsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    before do
      25.times do |i|
        Review.create!(
          content: "review #{i}"
        )
      end
    end

    it "returns paginated reviews with meta" do
      get reviews_url, headers: valid_headers, as: :json

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["data"].size).to eq(20)
      expect(body["meta"]).to include(
        "page" => 1,
        "limit" => 20,
        "total_count" => 25,
        "total_pages" => 2
      )
    end

    it "returns paginated reviews with meta for page 2" do
      get reviews_url, params: { page: 2 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["data"].size).to eq(5)
      expect(body["meta"]).to include(
        "page" => 2,
        "limit" => 20,
        "total_count" => 25,
        "total_pages" => 2
      )
    end

    it "respects limit parameter" do
      get reviews_url, params: { page: 2, limit: 10 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["data"].size).to eq(10)
      expect(body["meta"]).to include(
        "page" => 2,
        "limit" => 10,
        "total_count" => 25,
        "total_pages" => 3
      )
    end

    it "caps limit at 100" do
      get reviews_url, params: { limit: 999 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["data"].size).to eq(25)
      expect(body["meta"]).to include(
        "page" => 1,
        "limit" => 100,
        "total_count" => 25,
        "total_pages" => 1
      )
    end

    it "includes next_page and prev_page on a middle page" do
      get reviews_url, params: { page: 2, limit: 10 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["meta"]).to include(
        "page" => 2,
        "limit" => 10,
        "total_count" => 25,
        "total_pages" => 3,
        "next_page" => 3,
        "prev_page" => 1
      )
    end

    it "sets prev_page to nil on the first page" do
      get reviews_url, params: { page: 1, limit: 10 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["meta"]["prev_page"]).to be_nil
      expect(body["meta"]["next_page"]).to eq(2)
    end

    it "sets next_page to nil on the last page" do
      get reviews_url, params: { page: 3, limit: 10 }, headers: valid_headers

      expect(response).to be_successful
      body = response.parsed_body

      expect(body["meta"]["prev_page"]).to eq(2)
      expect(body["meta"]["next_page"]).to be_nil
    end
  end

  describe "GET /show" do
    it "returns not found" do
      get review_url(999), headers: valid_headers

      expect(response).to have_http_status(:not_found)
      body = response.parsed_body
      expect(body).to eq(
        "message" => "Review not found"
      )
    end
  end

  describe "POST /create" do
    it "returns bad request when content is missing" do
      post reviews_url, params: {}, headers: valid_headers, as: :json

      expect(response).to have_http_status(:bad_request)
      body = response.parsed_body
      expect(body).to eq(
        "message" => "param is missing or the value is empty or invalid: review"
      )
    end

    it "returns bad request for malformed JSON" do
      post reviews_url,
            params: '{"review": {"content": "hello"', headers: valid_headers.merge({ "CONTENT_TYPE" => "application/json" })

      expect(response).to have_http_status(:bad_request)
      body = response.parsed_body
      expect(body).to eq(
        "message" => "Error occurred while parsing request parameters"
      )
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        {
          content: "goodbye"
        }
      end

      it "updates the requested review" do
        review = Review.create! valid_attributes
        patch review_url(review),
              params: { review: new_attributes }, headers: valid_headers, as: :json
        review.reload
        expect(review).to have_attributes(content: "goodbye")
      end

      it "renders a JSON response with the review" do
        review = Review.create! valid_attributes
        patch review_url(review),
              params: { review: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the review" do
        review = Review.create! valid_attributes
        patch review_url(review),
              params: { review: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested review" do
      review = Review.create! valid_attributes
      expect {
        delete review_url(review), headers: valid_headers, as: :json
      }.to change(Review, :count).by(-1)
    end
  end
end
